version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"             # <- change host port to 3001
    depends_on:
      - drupal
    environment:
      NODE_ENV: production
      DRUPAL_BASE_URL: http://drupal:80
  drupal:
    image: drupal:10.2.4-php8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./backend/web:/var/www/html
    depends_on:
      - db
    environment:
      PHP_MEMORY_LIMIT: 512M
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
