parameters:
  cors.config:
    enabled: true
    allowedOrigins: ['http://localhost:3001']
    allowedHeaders: ['x-csrf-token','content-type','accept','authorization']
    allowedMethods: ['GET','OPTIONS']
    exposedHeaders: false
    maxAge: 1000
    supportsCredentials: false

services: {}
