name: Nightly Full

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      COMPOSE_PROJECT_NAME: qa
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Show Docker versions
        run: |
          docker --version
          docker compose version

      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Bring up stack (Docker Compose)
        run: |
          docker compose up -d
          docker ps --format 'table {{.Names}}\t{{.Ports}}'

      - name: Health checks (Drupal & Frontend)
        run: |
          for i in {1..60}; do curl -fsS http://localhost:8080/jsonapi/node/article && break || sleep 5; done
          for i in {1..60}; do curl -fsS http://localhost:3001 && break || sleep 5; done

      - name: PHPUnit
        run: vendor/bin/phpunit -v

      - name: Behat
        run: vendor/bin/behat -f progress

      - name: Cypress — full suite (Percy if token present)
        env:
          CYPRESS_baseUrl: http://frontend:3000
        run: |
          set -e
          DOCKER_NET="${COMPOSE_PROJECT_NAME}_default"
          docker run --rm \
            --network "$DOCKER_NET" \
            -e CYPRESS_baseUrl="$CYPRESS_baseUrl" \
            -e PERCY_TOKEN="$PERCY_TOKEN" \
            -v "$PWD/frontend":/e2e \
            -w /e2e \
            cypress/included:14.5.4 \
            bash -lc 'npm ci --no-audit --no-fund || npm i; npx cypress verify; \
              if [ -n "$PERCY_TOKEN" ]; then \
                npx percy exec -- cypress run --headless --browser electron --spec "cypress/e2e/**/*.cy.*"; \
              else \
                cypress run --headless --browser electron --spec "cypress/e2e/**/*.cy.*"; \
              fi'

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          if-no-files-found: ignore

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          if-no-files-found: ignore

      - name: Dump compose logs
        if: always()
        run: docker compose logs --no-color > compose-logs.txt || true

      - name: Upload compose logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: compose-logs.txt

      - name: Tear down
        if: always()
        run: docker compose down -v
